[package]
name = "suchbar"
description = "suchbar - enduser-learnable-language for database queries."
authors = ["Micha Glave <mig@xilab.net>",]
version = "0.5.0"
edition = "2021"
license = "MIT"
readme = "README.md"

[lib]

[dependencies]
pest = "2.6.0"
pest_derive = "2.6.0"
permeable = "0.3.1"
timewarp = "0.3.1"
