// search - section

value = ${ raw_string | PUSH("\"" | "'") ~ raw_string_interior ~ POP }
/// green
raw_string = { ( ASCII_ALPHANUMERIC | "." | "," | "-" | "/" | "\\ " )+ }
/// red
raw_string_interior = { ( !PEEK ~ ANY )* }

starts_with = { "^" }
ends_with = { "$" }
/// brown
from_to = { "-" ~ value }
term = { starts_with? ~ value ~ (ends_with | from_to )? }
/// orange
field_name = ${ ASCII_ALPHA ~ ( ASCII_ALPHANUMERIC | "_" | "-" )+ }
field = { field_name ~ invert? ~ eq ~ invert? ~ term }
eq = { "=" | "=>" | "=<" | ">" | "<" }
primary = _{ field | term | "(" ~ expr ~ ")" | "{" ~ expr ~ "}" | "[" ~ expr ~ "]" }
/// cyan
invert = { "!" | ^"NOT " }
atom = _{ invert? ~ primary }

bin_op = _{ and |  or }
    /// yellow
	and = { "+" | "&&" | ^"AND " }
	/// yellow
	or = { "||" | ^"OR " }

expr = { atom ~ (bin_op? ~ atom)* }

// sort - section
/// blue
sort_field = { ASCII_ALPHANUMERIC+ }
down = { "^" }
sort = { ";" ~ ( ","? ~ down? ~ sort_field )+ }

query = _{ SOI ~ expr? ~ sort? ~ EOI }

WHITESPACE = _{ " " }
