// search - section

value = ${ raw_string | PUSH("\"" | "'") ~ raw_string_interior ~ POP }
raw_char = _{ ( ASCII_ALPHANUMERIC | "." | "," | "/" | "\\ " ) }
/// green
raw_string = { ( ASCII_ALPHANUMERIC | "-" ) ~ raw_char+ }
/// red
raw_string_interior = { ( !PEEK ~ ANY )* }
    /// pink
    starts_with = { "^" | "*" }
    /// pink
    ends_with = { "$" | "*" }
/// brown
from_to = { "-" ~ value }
term = { (value ~ from_to | starts_with? ~ value ~ ends_with?) }
/// orange
field_name = ${ ASCII_ALPHA ~ ( ASCII_ALPHANUMERIC | "_" | "-" )+ }
    /// white
    eq = { "=" | "=>" | ">=" | "=<" | "<=" | ">" | "<" | "!=" | "=!" }
field = { field_name ~ eq ~ term }
primary = _{ field | term | "(" ~ expr ~ ")" | "{" ~ expr ~ "}" | "[" ~ expr ~ "]" }
/// cyan
invert = { "!" | ^"NOT " }
atom = _{ invert? ~ primary }

bin_op = _{ and |  or }
    /// yellow
	and = { "+" | "&&" | ^"AND " }
	/// yellow
	or = { "||" | ^"OR " }

expr = { atom ~ (bin_op? ~ atom)* }

// sort - section
/// blue
sort_field = { ASCII_ALPHANUMERIC+ }
down = { "^" }
sort = { ";" ~ ( ","? ~ down? ~ sort_field )+ }

query = _{ SOI ~ expr? ~ sort? ~ EOI }

WHITESPACE = _{ " " }
